create table cinema_row (row_no integer, shift bit, id bigint not null auto_increment, room_id bigint, primary key (id)) engine=InnoDB;
create table movie (release_date date, runtime integer, id bigint not null auto_increment, overview varchar(10000), director varchar(255), poster_path varchar(255), title varchar(255), primary key (id)) engine=InnoDB;
create table reservation (id bigint not null auto_increment, screening_id bigint, seat_id bigint, primary key (id)) engine=InnoDB;
create table room (room_number integer, id bigint not null auto_increment, primary key (id)) engine=InnoDB;
create table screening (id bigint not null auto_increment, movie_id bigint, room_id bigint, screening_time datetime(6), primary key (id)) engine=InnoDB;
create table seat (is_reserved bit not null, position_in_row integer, seat_number integer, id bigint not null auto_increment, row_id bigint, type varchar(255), primary key (id)) engine=InnoDB;
alter table cinema_row add constraint FK3yte56ropasc8xrtjlmcopl8e foreign key (room_id) references room (id);
alter table reservation add constraint FKsus9r7msj3uas10wxl1jvj8xb foreign key (screening_id) references screening (id);
alter table reservation add constraint FKewd3sohjspqf2sjjvdcmcefpb foreign key (seat_id) references seat (id);
alter table screening add constraint FKfp7sh76xc9m508stllspchnp9 foreign key (movie_id) references movie (id);
alter table screening add constraint FKd1m1np9gx570qj5ycbddv7fji foreign key (room_id) references room (id);
alter table seat add constraint FK21ue0n7c05nxewistjghydyhc foreign key (row_id) references cinema_row (id);